<a href="https://www.kaggle.com/code/ahmedfakhar123/pandas-toolkit-series-dataframes-filters?scriptVersionId=322722331" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# 🐼 Level 1: Introduction to Pandas

Welcome to the **Pandas Learning Series ⚡**

**Pandas** is a powerful Python library for working with structured data 📊 using **DataFrames** and **Series**. It helps in cleaning 🧹, analyzing 🔍, and preparing data for machine learning 🤖, and works well with NumPy and Matplotlib.

<div align=center>

<img src="https://images.decodo.com/Python_Pandas_1_cc44acf7dc/Python_Pandas_1_cc44acf7dc.png" width=700 />

</div>

### Key Uses of Pandas:

* **Data Analysis** 📈 — Find patterns and insights in data
* **Data Cleaning** 🧹 — Fix/remove missing or incorrect data
* **Data Exploration** 🔍 — Understand dataset structure and relationships

<div align=center>

<img src="https://www.datocms-assets.com/14946/1742484633-6683f897b1383d93497fbd5d_ad_4nxf2tnvvb852lmvmziifuwaczkerckindzqcdeawdxod5ebfs9zenxqd4e6vkck6jhfrs5whlredngeze6wvypv-fxjrwijc5pk3tj6ek3nw4vsi-t7zynb0tszajpbpf6q4jfmez8iz-gil7d5y1nfyemda.png" width=600 />

</div>

## 1.1 Why Use Pandas? 📊

Pandas is essential for handling **large, messy, real-world datasets** efficiently.

### Big Data 🌐

Big Data means datasets that are:

* 📦 Too large
* 🧩 Too complex
  for traditional tools.

### Data Science Role 🧠

Data Science is about collecting, organizing, and analyzing data to extract useful insights — and Pandas is a core tool for that.

### Data vs Information 🔄

* **Data:** Raw facts
* **Information:** Processed, meaningful data

👉 **Pandas helps turn data into useful information.**

<div align=center>

<img src="https://miro.medium.com/v2/resize:fit:1400/1*hPC7fpV0kAa-Z7xH4_-2BQ.png" width=600 />

</div>


## 1.2 What Can Pandas Do? 🐼

Pandas helps you perform common data operations easily:


<img src="https://img.shields.io/badge/Find%20Correlation-0EA5E9?style=for-the-badge" /> Understand relationships between columns/features (how one variable changes with another).

<img src="https://img.shields.io/badge/Calculate%20Average-6366F1?style=for-the-badge" /> Find mean values of data.

<img src="https://img.shields.io/badge/Find%20Min%20&%20Max-22C55E?style=for-the-badge" /> Get smallest and largest values in a dataset.

<img src="https://img.shields.io/badge/Handle%20Missing%20Data-F59E0B?style=for-the-badge" /> Remove or fix null/missing values.

<img src="https://img.shields.io/badge/Organize%20Data-E11D48?style=for-the-badge" /> Sort, filter, and reshape datasets efficiently.

👉 In short: **Pandas makes data analysis faster and easier.**

---

# 📊 Level 2: Getting Started — DataFrames & Exploration

## 2.1 Imorting Pandas

In [1]:
import pandas as pd

## 2.2 Checking version

In [2]:
pd.__version__

'2.3.3'

## 2.3 Creating DataFrame

We will discuss data frame in detail later, right now we will only see what is difference between data frame and dictionary

In [3]:
dataset1 = {
    "cars":["BMW", "Mercedes", "Rolls Royace"],
    "value":[1, 2, 3]
}
print(f"\nThis is basic Python dictionary:\n{dataset1}")
data_frame1 = pd.DataFrame(dataset1)
print(f"\nThis is data frame:\n{data_frame1}")

This is basic Python dictionary:
{'cars': ['BMW', 'Mercedes', 'Rolls Royace'], 'value': [1, 2, 3]}

This is data frame:
           cars  value
0           BMW      1
1      Mercedes      2
2  Rolls Royace      3

---

# 📘 Level 3: Pandas Series — Working with 1D Data

<div align="center">
    <img src="https://www.scaler.com/topics/images/pandas-series-thumbnail.webp" width=600>
</div>

## 3.1 What is Series?
Pandas Series is like a column iin a table, it is a one-dimensional array containing data of any type.

## 3.2 Conversion: LIST -> SERIES

In [4]:
list1 = [10, 20, 30, 40, 50]
series1 = pd.Series(list1)
print(f"\nPandas series looks like this:\n{series1}")

Pandas series looks like this:
0    10
1    20
2    30
3    40
4    50
dtype: int64

## 3.3 Conversion: NUMPY ARRAY -> SERIES

In [5]:
import numpy as np

array1 = np.array([100, 200, 300, 400, 500])
series2 = pd.Series(array1)
print(f"\nPandas series looks like this:\n{series2}")

Pandas series looks like this:
0    100
1    200
2    300
3    400
4    500
dtype: int64

## 3.4 Python List VS Pandas Series

| Feature        | List 🐍         | Series 🐼           |
| -------------- | --------------- | ------------------- |
| **Type**       | Python built-in | Pandas object       |
| **Index**      | Numeric only    | Custom or numeric   |
| **Operations** | Basic           | Advanced/vectorized |
| **Use**        | General purpose | Data analysis       |

👉 **List = simple container**
👉 **Series = labeled smart list** 🚀

## 3.5 Conversion: DICTIONARY -> SERIES

In [6]:
dictionary1 = {
    "a": "Earth",
    "b": "Mars",
    "c": "Jupiter",
    "d": "Saturn"
}

series3 = pd.Series(dictionary1)
print(f"\nPython Dictionary to Pandas series:\n{series3}")

Python Dictionary to Pandas series:
a      Earth
b       Mars
c    Jupiter
d     Saturn
dtype: object

---

# 📝 Level 4: Intermediate Pandas Series — Series Indexing

## 4.1 Series from Label Lists
Our task is to take the data and label values as seperated lists and create Pandas Series

In [7]:
labels = ["car1", "car2", "car3"]
cars = ["Honda", "Toyota", "BYD"]

car_series = pd.Series(data=cars, index=labels)
print(f"\nSeries with labels:\n{car_series}")

Series with labels:
car1     Honda
car2    Toyota
car3       BYD
dtype: object

## 4.2 Accessing items in Pandas Series
We can access an element of Pandas Series by indexing it's label/index

In [8]:
print(f"\nFirst element of `car_series`:\n{car_series["car1"]}")
print(f"\nSecond element of `car_series`:\n{car_series["car2"]}")
print(f"\nThird element of `car_series`:\n{car_series["car3"]}")

First element of `car_series`:
Honda

Second element of `car_series`:
Toyota

Third element of `car_series`:
BYD

---

# 🔢 Level 5: Advanced Pandas Series — Series Operations

## 5.1 Pandas Series Addition
Pandas Series addition is element-wise addition based on matching labels.

In [9]:
ser1 = pd.Series([50, 100, 150, 200], ["a", "b", "c", "d"])
ser2 = pd.Series([250, 300, 350, 400], ["b", "c", "d", "e"])

ser1 + ser2

a      NaN
b    350.0
c    450.0
d    550.0
e      NaN
dtype: float64

## 5.2 Addition using add() method

In [10]:
print(f"\nWith using add():\n{ser1.add(ser2)}")

With using add():
a      NaN
b    350.0
c    450.0
d    550.0
e      NaN
dtype: float64

When we use simple add() the result is same as direct addition, if we want to retain values of labels that does not match we can do like this:

In [11]:
print(f"\nWith using `fill_value` argument:\n{ser1.add(ser2, fill_value=0)}")

With using `fill_value` argument:
a     50.0
b    350.0
c    450.0
d    550.0
e    400.0
dtype: float64

## 5.3 Subtraction using sub() method

In [12]:
print(f"\nUsing `fill_value` argument while subtracting:\n{ser2.sub(ser1, fill_value=0)}")

Using `fill_value` argument while subtracting:
a    -50.0
b    150.0
c    150.0
d    150.0
e    400.0
dtype: float64

---

# 📑 Level 6: Python DataFrames — Mastering Tabular Data (2D Structure)

<div align="center">
    <img src="https://media.geeksforgeeks.org/wp-content/cdn-uploads/creating_dataframe1.png" width=600 />
</div>

A **DataFrame** is a **2-dimensional data structure in Pandas** used to store and organize data in a tabular format with **rows and columns**, where each column can have a different data type.

* DataFrames are the workhouse of Pandas
* They are directly inspired by R Programming Language
* We can think of it as bunch of Series objects put together

## 6.1 Creating a DataFrame

In [13]:
df = pd.DataFrame(
    np.random.rand(5, 6),
    index="A B C D E".split(),
    columns="U V W X Y Z".split()
)
df

          U         V         W         X         Y         Z
A  0.111094  0.551660  0.908490  0.784947  0.800412  0.039169
B  0.086114  0.593314  0.531145  0.930642  0.366024  0.586445
C  0.873453  0.788080  0.972577  0.833687  0.625898  0.057020
D  0.092753  0.055798  0.099530  0.364510  0.834379  0.080817
E  0.271162  0.330385  0.808810  0.129230  0.861511  0.852698

## 6.2 Accessing row and column of DataFrame

### Accessing Row

In [14]:
"""We cannot access row like this so later we will use loc and iloc to access row"""
# df["A"]
# This couses an error

'We cannot access row like this so later we will use loc and iloc to access row'

### Accessing Column

In [15]:
"""But we can access column directly like this"""
df["X"]

A    0.784947
B    0.930642
C    0.833687
D    0.364510
E    0.129230
Name: X, dtype: float64

## 6.3 Accessing multiple columns
To access multiple columns we can pass a list of columns

In [16]:
df[["X", "Y"]]
# Please note that we have to pass `list` of columns not just columns

          X         Y
A  0.784947  0.800412
B  0.930642  0.366024
C  0.833687  0.625898
D  0.364510  0.834379
E  0.129230  0.861511

## 6.4 Proof: DataFrame is bunch of Series

<div align="center">
    <img src="https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png" width=600 />
</div>

In [17]:
type(df["W"])

pandas.core.series.Series

So each column is a **Series**.

Meaning:

* **A DataFrame = multiple Series aligned together by index**

---

# 💡 Level 7: DataFrame Operations — Managing Columns

Explore how to **create, modify, and delete** columns in Pandas **DataFrames** to keep your data structured, flexible, and ready for analysis.

## 7.1 Creating DataFrame

In [18]:
data = pd.DataFrame(np.random.randn(4,6), columns=["A", "B", "C", "D", "E", "F"])
data

          A         B         C         D         E         F
0 -0.987353  0.475483  0.228430  0.280828 -1.792519 -0.397314
1 -1.795321 -1.374453  0.681725 -0.373462  0.332088  0.393376
2 -1.882722 -0.007640  0.247497  1.778539  0.395157 -0.913224
3  1.321688 -0.111190 -1.407143 -0.123912 -1.821484  0.962144

## 7.2 Adding Column

In [19]:
data["G"] = [10, 20, 30, 40]
data

          A         B         C         D         E         F   G
0 -0.987353  0.475483  0.228430  0.280828 -1.792519 -0.397314  10
1 -1.795321 -1.374453  0.681725 -0.373462  0.332088  0.393376  20
2 -1.882722 -0.007640  0.247497  1.778539  0.395157 -0.913224  30
3  1.321688 -0.111190 -1.407143 -0.123912 -1.821484  0.962144  40

## 7.2 Removing Column
We can remove column by simply using **.drop()** method

* **📌 Note:** Set the `axis` parameter to `1` when removing columns.

In [20]:
data.drop("A", axis=1)

          B         C         D         E         F   G
0  0.475483  0.228430  0.280828 -1.792519 -0.397314  10
1 -1.374453  0.681725 -0.373462  0.332088  0.393376  20
2 -0.007640  0.247497  1.778539  0.395157 -0.913224  30
3 -0.111190 -1.407143 -0.123912 -1.821484  0.962144  40

⚠️ By default, `.drop()` does **not** permanently modify the original DataFrame unless `inplace=True` is used.

In [21]:
data.drop("A", axis=1, inplace=True)
data

          B         C         D         E         F   G
0  0.475483  0.228430  0.280828 -1.792519 -0.397314  10
1 -1.374453  0.681725 -0.373462  0.332088  0.393376  20
2 -0.007640  0.247497  1.778539  0.395157 -0.913224  30
3 -0.111190 -1.407143 -0.123912 -1.821484  0.962144  40

---

# 🔍 Level 8: DataFrame Indexing — Selecting Specific Data

We will start by creting a random DataFrame of 2x2

In [22]:
randomData = pd.DataFrame(np.random.randint(100, 150, size=(3, 3)),
                          index=["2023 Sales", "2024 Sales", "2025 Sales"],
                          columns=["Product 1", "Product 2", "Product 3"])
randomData

            Product 1  Product 2  Product 3
2023 Sales        148        149        121
2024 Sales        110        129        141
2025 Sales        148        141        104

## 8.1 Selecting Column
We discussed earlier that we can access column directly as below

In [23]:
randomData["Product 1"]

2023 Sales    148
2024 Sales    110
2025 Sales    148
Name: Product 1, dtype: int64

## 8.2 Selecting Row
But we cannot select row **directly** from a DataFrame.

There are 2 methods to access row:
- **.loc[]** - uses label of row
- **.iloc[]** - uses index of row

### 8.2.1. Using .loc()

In [24]:
# Using loc[] for aceesing sales across Years 2023, 2024, 2025
print(randomData.loc["2023 Sales"], "\n")
print(randomData.loc["2024 Sales"], "\n")
print(randomData.loc["2025 Sales"], "\n")

Product 1    148
Product 2    149
Product 3    121
Name: 2023 Sales, dtype: int64

Product 1    110
Product 2    129
Product 3    141
Name: 2024 Sales, dtype: int64

Product 1    148
Product 2    141
Product 3    104
Name: 2025 Sales, dtype: int64

### 8.2.2 Using .iloc()

In [25]:
# Using iloc[] for aceesing sales across Years 2023, 2024, 2025
print(randomData.iloc[0], "\n")
print(randomData.iloc[1], "\n")
print(randomData.iloc[2], "\n")

Product 1    148
Product 2    149
Product 3    121
Name: 2023 Sales, dtype: int64

Product 1    110
Product 2    129
Product 3    141
Name: 2024 Sales, dtype: int64

Product 1    148
Product 2    141
Product 3    104
Name: 2025 Sales, dtype: int64

## 8.3 Selecting Particular Value

In [26]:
# Column-first look up (Uses label names)
print(f"The Sales of product 1 in 2024 is: {randomData['Product 1']['2024 Sales']}")

# Label-based look up (df.loc[row_label, col_label])
print(f"Using loc[]: {randomData.loc["2024 Sales", "Product 1"]}")

# Position-based look up (df.iloc[row_index, col_index])
print(f"Using iloc[]: {randomData.iloc[1, 0]}")

The Sales of product 1 in 2024 is: 110
Using loc[]: 110
Using iloc[]: 110

## 8.4 Selecting Subset of DataFrame

In [27]:
randomData.loc[["2023 Sales", "2024 Sales"], ["Product 2", "Product 3"]]

            Product 2  Product 3
2023 Sales        149        121
2024 Sales        129        141

---

# 🎯 Level 9: DataFrame Conditional Selection — Isolating Targets
An important feature of Pandas is **Conditional Selection** using bracket notation which is **very similar** to NumPy

In [28]:
randPopulation = pd.DataFrame(np.random.randint(10000000, 550000000, size=(3, 3)),
                          index=["2023 Population", "2024 Population", "2025 Population"],
                          columns=["Country 1", "Country 2", "Country 3"])
randPopulation

                 Country 1  Country 2  Country 3
2023 Population  331687261  533395245  348362833
2024 Population  218272474  252437027  408251586
2025 Population  298348029  262285346  389195286

## 9.1 Checking Population Conditions

Here, we check which country populations are greater than **300,000,000**.  
The result will return **True** for matching values and **False** for non-matching values.

In [29]:
randPopulation > 300000000

                 Country 1  Country 2  Country 3
2023 Population       True       True       True
2024 Population      False      False       True
2025 Population      False      False       True

## 9.2 Filtering Countries by Population

Now, we use the condition to filter the DataFrame and display only the population values greater than **300,000,000**.

In [30]:
randPopulation[randPopulation > 300000000]

                   Country 1    Country 2  Country 3
2023 Population  331687261.0  533395245.0  348362833
2024 Population          NaN          NaN  408251586
2025 Population          NaN          NaN  389195286

## 9.3 Filtering Rows with Conditions

How to filter rows in a **DataFrame** using conditions.  
We check values inside a `column` and display only the rows that satisfy the **condition**.

In [31]:
randPopulation[randPopulation["Country 1"] > 300000000]

                 Country 1  Country 2  Country 3
2023 Population  331687261  533395245  348362833

## 9.4 Filtering Rows & Selecting a Column

Filter rows where `"Country 1"` population is greater than `300000000`, then display only the `"Country 1"` column.

In [32]:
randPopulation[randPopulation["Country 1"] > 300000000]["Country 1"]

2023 Population    331687261
Name: Country 1, dtype: int64

---

# 💾 Level 10: Writing and Viewing Data — Input/Output

Quickly save your processed DataFrames to external files or inspect their contents directly in your notebook to verify your results.

### 🛠️ Key Operations

* **Viewing:** Use `.head()` or `.tail()` to quickly peek at your data.
* **Writing:** Use functions like `.to_csv()` or `.to_excel()` to export your work.

## 10.1 Reading CSV File

In [33]:
iPhoneData = pd.read_csv("/kaggle/input/datasets/jawadaahmed/iphone-sales-analytics-dataset/iphone_sales_dataset.csv")
iPhoneData

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5,1817,2025-05-01,Debit Card
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1,998,2025-03-05,PayPal
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5,876,2025-01-25,Credit Card
3,1004,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2,1290,2025-03-24,Debit Card
4,1005,Customer_5,USA,iPhone 15,128GB,Blue,3,1092,2025-02-01,Debit Card
...,...,...,...,...,...,...,...,...,...,...
95,1096,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1,1743,2025-03-09,Credit Card
96,1097,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3,1671,2025-02-08,Credit Card
97,1098,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4,1125,2025-01-08,Debit Card
98,1099,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5,1540,2025-02-04,Debit Card
99,1100,Customer_100,UK,iPhone 15,512GB,Blue,3,1549,2025-03-28,Debit Card

## 10.2 Converting to string

In [34]:
print(iPhoneData.to_string())

    Order_ID Customer_Name   Country       iPhone_Model Storage   Color  Quantity  Price   Sale_Date Payment_Method
0       1001    Customer_1       USA          iPhone 13   256GB  Purple         5   1817  2025-05-01     Debit Card
1       1002    Customer_2    Canada          iPhone 12   256GB    Blue         1    998  2025-03-05         PayPal
2       1003    Customer_3    Canada  iPhone 15 Pro Max   512GB   Black         5    876  2025-01-25    Credit Card
3       1004    Customer_4       USA  iPhone 15 Pro Max   512GB   Black         2   1290  2025-03-24     Debit Card
4       1005    Customer_5       USA          iPhone 15   128GB    Blue         3   1092  2025-02-01     Debit Card
5       1006    Customer_6       UAE      iPhone 14 Pro   256GB     Red         5   1939  2025-02-15     Debit Card
6       1007    Customer_7   Germany      iPhone 14 Pro   512GB    Blue         1   1798  2025-02-13     Debit Card
7       1008    Customer_8        UK  iPhone 15 Pro Max   128GB  Purple         3   1808  2025-03-30     Debit Card
8       1009    Customer_9       UAE          iPhone 12   512GB  Purple         2   1381  2025-03-06     Debit Card
9       1010   Customer_10  Pakistan      iPhone 14 Pro   128GB     Red         5   1670  2025-02-25     Debit Card
10      1011   Customer_11        UK  iPhone 15 Pro Max   256GB   White         5   1857  2025-01-28         PayPal
11      1012   Customer_12       USA          iPhone 14   128GB   Black         3   1572  2025-03-25           Cash
12      1013   Customer_13   Germany          iPhone 12   512GB    Blue         3   1868  2025-02-18         PayPal
13      1014   Customer_14       USA          iPhone 12   512GB   Black         3   1743  2025-01-17    Credit Card
14      1015   Customer_15       UAE      iPhone 14 Pro   256GB    Blue         1   1544  2025-01-27    Credit Card
15      1016   Customer_16       UAE          iPhone 12   128GB    Blue         4   1819  2025-04-04     Debit Card
16      1017   Customer_17   Germany          iPhone 13   512GB     Red         5   1992  2025-04-28         PayPal
17      1018   Customer_18    Canada      iPhone 14 Pro   256GB     Red         2   1003  2025-04-04         PayPal
18      1019   Customer_19       UAE          iPhone 13   128GB  Purple         1   1010  2025-03-15     Debit Card
19      1020   Customer_20       UAE          iPhone 15   256GB  Purple         3   1588  2025-03-27     Debit Card
20      1021   Customer_21  Pakistan          iPhone 15   256GB     Red         3    742  2025-03-12           Cash
21      1022   Customer_22  Pakistan          iPhone 15   128GB   Black         4   1627  2025-03-22         PayPal
22      1023   Customer_23       USA          iPhone 15   128GB     Red         5   1964  2025-04-19           Cash
23      1024   Customer_24        UK          iPhone 15   256GB   White         4    817  2025-01-01           Cash
24      1025   Customer_25        UK  iPhone 15 Pro Max   128GB  Purple         5   1571  2025-01-23     Debit Card
25      1026   Customer_26       UAE          iPhone 14   128GB     Red         3   1302  2025-03-27     Debit Card
26      1027   Customer_27       USA          iPhone 13   256GB   White         5   1060  2025-01-19           Cash
27      1028   Customer_28        UK          iPhone 13   128GB    Blue         4   1879  2025-01-30    Credit Card
28      1029   Customer_29    Canada      iPhone 14 Pro   256GB     Red         3   1963  2025-03-30     Debit Card
29      1030   Customer_30    Canada          iPhone 14   512GB    Blue         5   1673  2025-01-19     Debit Card
30      1031   Customer_31       UAE          iPhone 13   256GB  Purple         5   1135  2025-03-26     Debit Card
31      1032   Customer_32       USA  iPhone 15 Pro Max   128GB    Blue         5   1550  2025-03-09         PayPal
32      1033   Customer_33    Canada          iPhone 14   128GB    Blue         5   1646  2025-02-05         PayPal
33      1034   Customer_34       USA      iPhone 14 Pro   128GB     Red         4   1559  2025-03-17     Debit Card
34      1035   Customer_35    Canada      iPhone 14 Pro   128GB   White         5   1793  2025-01-02           Cash
35      1036   Customer_36       USA          iPhone 12   512GB    Blue         5   1030  2025-04-02    Credit Card
36      1037   Customer_37    Canada      iPhone 14 Pro   128GB     Red         2   1921  2025-04-09    Credit Card
37      1038   Customer_38       UAE      iPhone 14 Pro   128GB  Purple         1   1674  2025-04-17    Credit Card
38      1039   Customer_39    Canada  iPhone 15 Pro Max   256GB     Red         1   1218  2025-01-25    Credit Card
39      1040   Customer_40       UAE  iPhone 15 Pro Max   256GB  Purple         4   1034  2025-05-01    Credit Card
40      1041   Customer_41        UK          iPhone 15   128GB   Black         3   1633  2025-03-27    Credit Card
41      1042   Customer_42        UK          iPhone 15   256GB   Black         4    720  2025-01-20     Debit Card
42      1043   Customer_43       UAE          iPhone 15   128GB     Red         2   1238  2025-03-22    Credit Card
43      1044   Customer_44       USA          iPhone 13   256GB   White         4   1779  2025-01-12     Debit Card
44      1045   Customer_45        UK          iPhone 13   256GB  Purple         5   1667  2025-04-18     Debit Card
45      1046   Customer_46   Germany  iPhone 15 Pro Max   512GB    Blue         1   1094  2025-01-12         PayPal
46      1047   Customer_47       USA          iPhone 12   256GB   White         5   1120  2025-01-11         PayPal
47      1048   Customer_48       USA          iPhone 14   256GB   Black         5   1786  2025-03-28           Cash
48      1049   Customer_49    Canada          iPhone 14   128GB   Black         1   1199  2025-03-27     Debit Card
49      1050   Customer_50    Canada      iPhone 14 Pro   128GB    Blue         1    733  2025-01-12           Cash
50      1051   Customer_51        UK  iPhone 15 Pro Max   256GB    Blue         5   1113  2025-01-22    Credit Card
51      1052   Customer_52  Pakistan          iPhone 14   512GB    Blue         5    764  2025-03-12     Debit Card
52      1053   Customer_53       USA      iPhone 14 Pro   128GB   Black         1   1959  2025-02-27         PayPal
53      1054   Customer_54        UK          iPhone 14   256GB   White         1   1829  2025-04-24    Credit Card
54      1055   Customer_55  Pakistan      iPhone 14 Pro   128GB    Blue         2    899  2025-04-10         PayPal
55      1056   Customer_56       USA          iPhone 15   512GB   Black         5   1250  2025-01-02     Debit Card
56      1057   Customer_57  Pakistan      iPhone 14 Pro   256GB    Blue         1    945  2025-05-01     Debit Card
57      1058   Customer_58        UK  iPhone 15 Pro Max   256GB  Purple         5   1752  2025-04-11     Debit Card
58      1059   Customer_59  Pakistan      iPhone 14 Pro   512GB     Red         4   1909  2025-04-13     Debit Card
59      1060   Customer_60   Germany      iPhone 14 Pro   512GB    Blue         5   1714  2025-01-12    Credit Card
60      1061   Customer_61       UAE          iPhone 15   512GB   Black         5   1519  2025-02-21     Debit Card
61      1062   Customer_62    Canada          iPhone 13   512GB  Purple         4   1769  2025-04-05         PayPal
62      1063   Customer_63    Canada  iPhone 15 Pro Max   128GB   White         5   1644  2025-02-21    Credit Card
63      1064   Customer_64        UK  iPhone 15 Pro Max   512GB     Red         2   1991  2025-01-28           Cash
64      1065   Customer_65    Canada          iPhone 14   256GB   White         3   1706  2025-01-04     Debit Card
65      1066   Customer_66       USA          iPhone 14   256GB   White         1   1884  2025-03-28     Debit Card
66      1067   Customer_67    Canada      iPhone 14 Pro   128GB    Blue         3   1027  2025-04-22     Debit Card
67      1068   Customer_68  Pakistan  iPhone 15 Pro Max   128GB   Black         2    788  2025-04-05    Credit Card
68      1069   Customer_69   Germany      iPhone 14 Pro   128GB   White         3    796  2025-01-25         PayPal
69      1070   Customer_70    Canada      iPhone 14 Pro   512GB    Blue         4   1829  2025-01-13    Credit Card
70      1071   Customer_71        UK          iPhone 12   512GB  Purple         2   1977  2025-01-10           Cash
71      1072   Customer_72       UAE          iPhone 12   128GB     Red         5   1964  2025-02-06     Debit Card
72      1073   Customer_73       USA      iPhone 14 Pro   128GB     Red         2   1629  2025-01-28           Cash
73      1074   Customer_74   Germany  iPhone 15 Pro Max   256GB   White         1   1987  2025-04-25         PayPal
74      1075   Customer_75   Germany          iPhone 14   512GB    Blue         4   1547  2025-01-10           Cash
75      1076   Customer_76        UK      iPhone 14 Pro   256GB     Red         5   1923  2025-04-12           Cash
76      1077   Customer_77       UAE      iPhone 14 Pro   512GB    Blue         2   1477  2025-02-27         PayPal
77      1078   Customer_78  Pakistan          iPhone 13   128GB  Purple         4   1464  2025-01-15           Cash
78      1079   Customer_79       USA          iPhone 15   128GB  Purple         3   1790  2025-02-12    Credit Card
79      1080   Customer_80       USA          iPhone 15   512GB  Purple         4   1819  2025-02-24     Debit Card
80      1081   Customer_81  Pakistan          iPhone 13   256GB  Purple         5   1579  2025-03-05    Credit Card
81      1082   Customer_82        UK  iPhone 15 Pro Max   256GB    Blue         1    756  2025-03-28     Debit Card
82      1083   Customer_83        UK      iPhone 14 Pro   128GB   White         3   1165  2025-03-08           Cash
83      1084   Customer_84   Germany          iPhone 13   256GB     Red         5   1229  2025-03-22           Cash
84      1085   Customer_85        UK          iPhone 12   256GB   White         4   1656  2025-04-12           Cash
85      1086   Customer_86   Germany          iPhone 12   256GB   Black         2    950  2025-04-08           Cash
86      1087   Customer_87    Canada          iPhone 15   128GB   White         1   1903  2025-01-02         PayPal
87      1088   Customer_88        UK  iPhone 15 Pro Max   512GB  Purple         5    718  2025-02-04           Cash
88      1089   Customer_89       USA          iPhone 13   256GB   White         3   1249  2025-01-12     Debit Card
89      1090   Customer_90       USA          iPhone 12   256GB   White         3    887  2025-02-17     Debit Card
90      1091   Customer_91       UAE          iPhone 15   256GB     Red         5   1357  2025-03-22         PayPal
91      1092   Customer_92       UAE  iPhone 15 Pro Max   256GB   White         3   1361  2025-02-10    Credit Card
92      1093   Customer_93        UK          iPhone 12   256GB   Black         3   1971  2025-01-20    Credit Card
93      1094   Customer_94       USA  iPhone 15 Pro Max   512GB   White         1   1622  2025-03-22    Credit Card
94      1095   Customer_95    Canada          iPhone 13   128GB   White         4   1388  2025-01-06    Credit Card
95      1096   Customer_96       UAE      iPhone 14 Pro   256GB    Blue         1   1743  2025-03-09    Credit Card
96      1097   Customer_97        UK  iPhone 15 Pro Max   512GB   White         3   1671  2025-02-08    Credit Card
97      1098   Customer_98        UK  iPhone 15 Pro Max   512GB   White         4   1125  2025-01-08     Debit Card
98      1099   Customer_99   Germany  iPhone 15 Pro Max   512GB  Purple         5   1540  2025-02-04     Debit Card
99      1100  Customer_100        UK          iPhone 15   512GB    Blue         3   1549  2025-03-28     Debit Card

## 10.3 Accessing first 5 entries

In [35]:
iPhoneData.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5,1817,2025-05-01,Debit Card
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1,998,2025-03-05,PayPal
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5,876,2025-01-25,Credit Card
3,1004,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2,1290,2025-03-24,Debit Card
4,1005,Customer_5,USA,iPhone 15,128GB,Blue,3,1092,2025-02-01,Debit Card

## 10.4 Accessing last five entires

In [36]:
iPhoneData.tail()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
95,1096,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1,1743,2025-03-09,Credit Card
96,1097,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3,1671,2025-02-08,Credit Card
97,1098,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4,1125,2025-01-08,Debit Card
98,1099,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5,1540,2025-02-04,Debit Card
99,1100,Customer_100,UK,iPhone 15,512GB,Blue,3,1549,2025-03-28,Debit Card

## 10.5 Viewing DataFrame Information

Use `iPhoneData.info()` to display a summary of the **DataFrame**, including column names, data types, non-null values, and memory usage.

In [37]:
iPhoneData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Customer_Name   100 non-null    object
 2   Country         100 non-null    object
 3   iPhone_Model    100 non-null    object
 4   Storage         100 non-null    object
 5   Color           100 non-null    object
 6   Quantity        100 non-null    int64
 7   Price           100 non-null    int64
 8   Sale_Date       100 non-null    object
 9   Payment_Method  100 non-null    object
dtypes: int64(3), object(7)
memory usage: 7.9+ KB