<a href="https://www.kaggle.com/code/ahmedfakhar123/pandas-project-ai-dataset-preprocessing-eda?scriptVersionId=334782485" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
---
# 📌 1. Introduction

Data preprocessing and ***Exploratory Data Analysis (EDA)*** are fundamental steps in every data science and machine learning workflow. Before building any model, it is essential to understand the dataset, identify data quality issues, clean inconsistencies, and explore meaningful patterns.

In this project, we will use the ***Titanic*** dataset to perform a complete preprocessing and EDA workflow using ***Pandas***. The notebook covers data exploration, handling missing values, removing duplicate records, feature engineering, statistical analysis, and data visualization.

By the end of this project, the dataset will be ***clean, well-understood, and ready for machine learning***, while also revealing valuable insights into the factors that influenced passenger survival.


## 🎯 Objectives
1. ***📥 Load and inspect the dataset***
2. ***🔍 Explore its structure and statistics***
3. ***🧹 Clean and preprocess the data***
4. ***⚙️ Perform feature engineering***
5. ***📊 Conduct Exploratory Data Analysis (EDA)***
6. ***📈 Visualize trends and relationships***
7. ***💡 Extract meaningful insights***
8. ***💾 Export the cleaned dataset***

---

# 📂 2. Import Libraries

To perform ***data preprocessing***, ***analysis***, and ***visualization***, we first import the required Python libraries. Each library provides ***specialized tools*** that simplify working with datasets, from loading and cleaning data to generating ***informative visualizations.***

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

---

# 📥 3. Load the Dataset

The first step is to load the ***Titanic dataset*** into a `Pandas DataFrame`. Once loaded, we can begin ***exploring*** its structure, examine the available features, and prepare it for ***preprocessing*** and ***exploratory data analysis.***

In [2]:
df = pd.read_csv("/kaggle/input/datasets/marcpaulo/titanic-huge-dataset-1m-passengers/huge_1M_titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1001305,0,2,"Name1001305, Mr. Surname1001305",male,27.0,0,0,244358,26.196512,NaN,S
999996,1001306,1,1,"Name1001306, Miss. Surname1001306",female,33.0,0,0,349221,102.555248,NaN,S
999997,1001307,0,3,"Name1001307, Mr. Surname1001307",male,NaN,1,0,PC 17601,8.274807,NaN,S
999998,1001308,0,2,"Name1001308, Mr. Surname1001308",male,35.0,1,0,112050,0.000000,B102,S
999999,1001309,1,1,"Name1001309, Miss. Surname1001309",female,37.0,1,0,28403,57.720316,NaN,S

---

# 👀 4. Dataset Overview
Before cleaning or analyzing the data, it's important to understand the ***dataset's structure*** and ***contents.*** This section provides a ***quick overview*** of the dataset, helping us identify its ***size***, ***features***, ***data types***, and ***basic statistical characteristics***.

## 4.1 Display First & Last Rows
View the ***first*** and ***last*** few records of the dataset to get a ***quick understanding*** of its structure, values, and overall format.

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [4]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
999995,1001305,0,2,"Name1001305, Mr. Surname1001305",male,27.0,0,0,244358,26.196512,NaN,S
999996,1001306,1,1,"Name1001306, Miss. Surname1001306",female,33.0,0,0,349221,102.555248,NaN,S
999997,1001307,0,3,"Name1001307, Mr. Surname1001307",male,NaN,1,0,PC 17601,8.274807,NaN,S
999998,1001308,0,2,"Name1001308, Mr. Surname1001308",male,35.0,1,0,112050,0.000000,B102,S
999999,1001309,1,1,"Name1001309, Miss. Surname1001309",female,37.0,1,0,28403,57.720316,NaN,S

## 4.2 Dataset Shape
Determine the ***number of rows and columns*** to understand the ***size and dimensions*** of the dataset.

In [5]:
df.shape

(1000000, 12)

This shows that `df` has ***1000000 rows*** and ***12 columns***

* Dataset Shape
* Column Names
* Data Types
* Dataset Information
* Statistical Summary


---

## 🔎 5. Initial Data Exploration

* Check Missing Values
* Check Duplicate Records
* Unique Values per Column
* Memory Usage *(optional)*

---

## 🧹 6. Data Cleaning

* Handle Missing Values
* Remove Duplicates
* Fix Data Types (if required)
* Rename Columns (if required)
* Verify Cleaned Dataset

---

## ⚙️ 7. Feature Engineering

* Create New Features *(e.g., Family Size = SibSp + Parch + 1)*
* Categorize Age Groups
* Extract Passenger Titles from Names *(optional)*

---

## 📊 8. Exploratory Data Analysis (EDA)

### 🎯 Survival Analysis

* Overall Survival Rate
* Survival by Gender
* Survival by Passenger Class
* Survival by Age Group
* Survival by Embarkation Port

### 👥 Passenger Demographics

* Age Distribution
* Gender Distribution
* Passenger Class Distribution
* Family Size Distribution

### 💰 Fare Analysis

* Fare Distribution
* Fare by Passenger Class
* Fare vs Survival

### 🔗 Relationship Analysis

* Correlation Matrix
* Pairwise Relationships *(optional)*

---

## 📈 9. Data Visualization

* 📊 Bar Charts
* 📈 Histograms
* 📦 Box Plots
* ⚪ Scatter Plots
* 🔥 Heatmap
* 🥧 Pie Charts *(optional)*

---

## 💡 10. Key Insights

Example:

* Female passengers had a significantly higher survival rate.
* First-class passengers survived more often.
* Younger passengers generally had better survival chances.
* Higher ticket fares were associated with increased survival.

---

## 💾 11. Export the Cleaned Dataset

---

## ✅ 12. Conclusion

---

## 📚 13. Next Steps

* Build a Machine Learning model
* Perform Feature Selection
* Train Classification Algorithms

---

## ❤️ Support

If you found this notebook helpful, consider **upvoting ⭐** it and sharing your feedback. Contributions and suggestions are always welcome!

---
---