<a href="https://www.kaggle.com/code/ahmedfakhar123/pandas-basics-step-by-step-practice?scriptVersionId=322106195" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# 🐼 Level 1: Introduction to Pandas

Welcome to the **Pandas Learning Series ⚡**

**Pandas** is a powerful Python library for working with structured data 📊 using **DataFrames** and **Series**. It helps in cleaning 🧹, analyzing 🔍, and preparing data for machine learning 🤖, and works well with NumPy and Matplotlib.

<div align=center>

<img src="https://images.decodo.com/Python_Pandas_1_cc44acf7dc/Python_Pandas_1_cc44acf7dc.png" width=700 />

</div>

### Key Uses of Pandas:

* **Data Analysis** 📈 — Find patterns and insights in data
* **Data Cleaning** 🧹 — Fix/remove missing or incorrect data
* **Data Exploration** 🔍 — Understand dataset structure and relationships

<div align=center>

<img src="https://www.datocms-assets.com/14946/1742484633-6683f897b1383d93497fbd5d_ad_4nxf2tnvvb852lmvmziifuwaczkerckindzqcdeawdxod5ebfs9zenxqd4e6vkck6jhfrs5whlredngeze6wvypv-fxjrwijc5pk3tj6ek3nw4vsi-t7zynb0tszajpbpf6q4jfmez8iz-gil7d5y1nfyemda.png" width=600 />

</div>

---

## 1.1 Why Use Pandas? 📊

Pandas is essential for handling **large, messy, real-world datasets** efficiently.

### Big Data 🌐

Big Data means datasets that are:

* 📦 Too large
* 🧩 Too complex
  for traditional tools.

### Data Science Role 🧠

Data Science is about collecting, organizing, and analyzing data to extract useful insights — and Pandas is a core tool for that.

### Data vs Information 🔄

* **Data:** Raw facts
* **Information:** Processed, meaningful data

<div align=center>

<img src="https://miro.medium.com/v2/resize:fit:1400/1*hPC7fpV0kAa-Z7xH4_-2BQ.png" width=600 />

</div>

👉 **Pandas helps turn data into useful information.**

---

## 1.2 What Can Pandas Do? 🐼

Pandas helps you perform common data operations easily:


<img src="https://img.shields.io/badge/Find%20Correlation-0EA5E9?style=for-the-badge" /> Understand relationships between columns/features (how one variable changes with another).

<img src="https://img.shields.io/badge/Calculate%20Average-6366F1?style=for-the-badge" /> Find mean values of data.

<img src="https://img.shields.io/badge/Find%20Min%20&%20Max-22C55E?style=for-the-badge" /> Get smallest and largest values in a dataset.

<img src="https://img.shields.io/badge/Handle%20Missing%20Data-F59E0B?style=for-the-badge" /> Remove or fix null/missing values.

<img src="https://img.shields.io/badge/Organize%20Data-E11D48?style=for-the-badge" /> Sort, filter, and reshape datasets efficiently.

👉 In short: **Pandas makes data analysis faster and easier.**

---

# 📊 Level 2: Getting Started — DataFrames & Exploration

## 2.1 Imorting Pandas

In [1]:
import pandas as pd

## 2.2 Checking version

In [2]:
pd.__version__

'2.3.3'

## 2.3 Creating DataFrame

We will discuss data frame in detail later, right now we will only see what is difference between data frame and dictionary

In [3]:
dataset1 = {
    "cars":["BMW", "Mercedes", "Rolls Royace"],
    "value":[1, 2, 3]
}
print(f"\nThis is basic Python dictionary:\n{dataset1}")
data_frame1 = pd.DataFrame(dataset1)
print(f"\nThis is data frame:\n{data_frame1}")

This is basic Python dictionary:
{'cars': ['BMW', 'Mercedes', 'Rolls Royace'], 'value': [1, 2, 3]}

This is data frame:
           cars  value
0           BMW      1
1      Mercedes      2
2  Rolls Royace      3

---

# 📘 Level 3: Pandas Series — Working with 1D Data

## 3.1 What is Series?
Pandas Series is like a column iin a table, it is a one-dimensional array containing data of any type.

## 3.2 Conversion: LIST -> SERIES

In [4]:
list1 = [10, 20, 30, 40, 50]
series1 = pd.Series(list1)
print(f"\nPandas series looks like this:\n{series1}")

Pandas series looks like this:
0    10
1    20
2    30
3    40
4    50
dtype: int64

## 3.3 Conversion: NUMPY ARRAY -> SERIES

In [5]:
import numpy as np

array1 = np.array([100, 200, 300, 400, 500])
series2 = pd.Series(array1)
print(f"\nPandas series looks like this:\n{series2}")

Pandas series looks like this:
0    100
1    200
2    300
3    400
4    500
dtype: int64

## 3.4 Python List VS Pandas Series

| Feature        | List 🐍         | Series 🐼           |
| -------------- | --------------- | ------------------- |
| **Type**       | Python built-in | Pandas object       |
| **Index**      | Numeric only    | Custom or numeric   |
| **Operations** | Basic           | Advanced/vectorized |
| **Use**        | General purpose | Data analysis       |

👉 **List = simple container**
👉 **Series = labeled smart list** 🚀

## 3.5 Conversion: DICTIONARY -> SERIES

In [6]:
dictionary1 = {
    "a": "Earth",
    "b": "Mars",
    "c": "Jupiter",
    "d": "Saturn"
}

series3 = pd.Series(dictionary1)
print(f"\nPython Dictionary to Pandas series:\n{series3}")

Python Dictionary to Pandas series:
a      Earth
b       Mars
c    Jupiter
d     Saturn
dtype: object

---

# 📝 Level 4: Intermediate Pandas Series — Series Indexing

## 4.1 Series from Label Lists
Our task is to take the data and label values as seperated lists and create Pandas Series

In [7]:
labels = ["car1", "car2", "car3"]
cars = ["Honda", "Toyota", "BYD"]

car_series = pd.Series(data=cars, index=labels)
print(f"\nSeries with labels:\n{car_series}")

Series with labels:
car1     Honda
car2    Toyota
car3       BYD
dtype: object

## 4.2 Accessing items in Pandas Series
We can access an element of Pandas Series by indexing it's label/index

In [8]:
print(f"\nFirst element of `car_series`:\n{car_series["car1"]}")
print(f"\nSecond element of `car_series`:\n{car_series["car2"]}")
print(f"\nThird element of `car_series`:\n{car_series["car3"]}")

First element of `car_series`:
Honda

Second element of `car_series`:
Toyota

Third element of `car_series`:
BYD

---

# 🔢 Level 5: Advanced Pandas Series — Series Operations

## 5.1 Pandas Series Addition
Pandas Series addition is element-wise addition based on matching labels.

In [9]:
ser1 = pd.Series([50, 100, 150, 200], ["a", "b", "c", "d"])
ser2 = pd.Series([250, 300, 350, 400], ["b", "c", "d", "e"])

ser1 + ser2

a      NaN
b    350.0
c    450.0
d    550.0
e      NaN
dtype: float64

## 5.2 Addition using add() method

In [10]:
print(f"\nWith using add():\n{ser1.add(ser2)}")

With using add():
a      NaN
b    350.0
c    450.0
d    550.0
e      NaN
dtype: float64

When we use simple add() the result is same as direct addition, if we want to retain values of labels that does not match we can do like this:

In [11]:
print(f"\nWith using `fill_value` argument:\n{ser1.add(ser2, fill_value=0)}")

With using `fill_value` argument:
a     50.0
b    350.0
c    450.0
d    550.0
e    400.0
dtype: float64

## 5.3 Subtraction using sub() method

In [12]:
print(f"\nUsing `fill_value` argument while subtracting:\n{ser2.sub(ser1, fill_value=0)}")

Using `fill_value` argument while subtracting:
a    -50.0
b    150.0
c    150.0
d    150.0
e    400.0
dtype: float64

---

# 📑 Level 6: Python DataFrames— Mastering Tabular Data (2D Structure)
A **DataFrame** is a **2-dimensional data structure in Pandas** used to store and organize data in a tabular format with **rows and columns**, where each column can have a different data type.

* DataFrames are the workhouse of Pandas
* They are directly inspired by R Programming Language
* We can think of it as bunch of Series objects put together

## 6.1 Creating a DataFrame

In [13]:
df = pd.DataFrame(
    np.random.rand(5, 6),
    index="A B C D E".split(),
    columns="U V W X Y Z".split()
)
df

          U         V         W         X         Y         Z
A  0.873566  0.967541  0.639978  0.300079  0.993615  0.889951
B  0.985433  0.594522  0.799202  0.305633  0.952796  0.238213
C  0.403106  0.290695  0.969119  0.427438  0.294295  0.884879
D  0.567596  0.982378  0.116215  0.156939  0.080806  0.477508
E  0.616331  0.402685  0.038646  0.349190  0.250543  0.975196

## 6.2 Accessing row and column of DataFrame

### Accessing Row

In [14]:
"""We cannot access row like this so later we will use loc and iloc to access row"""
# df["A"]
# This couses an error

'We cannot access row like this so later we will use loc and iloc to access row'

### Accessing Column

In [15]:
"""But we can access column directly like this"""
df["X"]

A    0.300079
B    0.305633
C    0.427438
D    0.156939
E    0.349190
Name: X, dtype: float64

## 6.3 Accessing multiple columns
To access multiple columns we can pass a list of columns

In [16]:
df[["X", "Y"]]
# Please note that we have to pass `list` of columns not just columns

          X         Y
A  0.300079  0.993615
B  0.305633  0.952796
C  0.427438  0.294295
D  0.156939  0.080806
E  0.349190  0.250543

## 6.4 Proof: DataFrame is bunch of Series

In [17]:
type(df["W"])

pandas.core.series.Series

So each column is a **Series**.

Meaning:

* **A DataFrame = multiple Series aligned together by index**

---